<?php
/** @var \Magento\Backend\Block\Template $block */
$labelAddRow = $block->getData('label_add_row');
?>
<div class="admin__field field with-note">
    <label class="label admin__field-label">&nbsp;</label>
    <div class="admin__field-control control">
        <a href="#" class="clone_new"><?= $labelAddRow ?: '[Add Slide]' ?></a>
    </div>
</div>

<script>
    require([
        'jquery',
        'jquery/ui'
    ], function ($) {

        // Al dar click en "Add Slide", clonamos la fila oculta
        $(document).off('click', 'fieldset.dynamic .clone_new');
        $(document).on('click', 'fieldset.dynamic .clone_new', function(e) {
            e.preventDefault();
            let $fieldset = $(this).parents('fieldset.dynamic');
            let $toClone  = $fieldset.find('.field-to-clone').first();
            let $newRow   = $toClone.clone().removeClass('field-to-clone').addClass('field-clone');
            $newRow.show();
            $newRow.appendTo($fieldset.find('.content'));
            initSortable();
        });

        // Eliminar fila
        $(document).off('click', 'fieldset.dynamic .clone_remove');
        $(document).on('click', 'fieldset.dynamic .clone_remove', function(e) {
            e.preventDefault();
            $(this).parents('.field-clone').remove();
            initSortable();
        });

        function initSortable() {
            $('fieldset.dynamic .content').sortable();
        }

        initSortable();
    });
</script>
