<div class="personal-footer-theme">
    <div class="footer-content">
        <div class="footer-content-item">
            <div class="footer-content-item-title">
                <h3>Sobre nosotros</h3>
            </div>
            <div class="footer-content-item-content">
                <ul>
                    <li><a href="#">Nuestra historia</a></li>
                    <li><a href="#">Trabaja con nosotros</a></li>
                    <li><a href="#">Prensa</a></li>
                </ul>
            </div>
        </div>
        <div class="footer-content-item">
            <div class="footer-content-item-title">
                <h3>Soporte</h3>
            </div>
            <div class="footer-content-item-content">
                <ul>
                    <li><a href="#">Centro de ayuda</a></li>
                    <li><a href="#">Devoluciones</a></li>
                    <li><a href="#">Información de envío</a></li>
                </ul>
            </div>
        </div>
        <div class="footer-content-item">
            <div class="footer-content-item-title">
                <h3>Legal</h3>
            </div>
            <div class="footer-content-item-content">
                <ul>
                    <li><a href="#">Políticas de privacidad</a></li>
                    <li><a href="#">Terminos y condiciones</a></li>
                    <li><a href="#">Política de cookies</a></li>
                </ul>
            </div>
        </div>
        <div class="footer-content-item">
            <div class="footer-content-item-title">
                <h3>Conecta con nosotros</h3>
            </div>
            <div class="footer-content-item-content">
                <ul class="social-media-links">
                    <li>
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-twitter h-5 w-5"><path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z"></path></svg>
                        <span class="sr-only">Twitter</span>    
                    </li>
                    <li>
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-instagram h-5 w-5"><rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path><line x1="17.5" x2="17.51" y1="6.5" y2="6.5"></line></svg>
                        <span class="sr-only">Instagram</span>
                    </li>
                    <li>
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-github h-5 w-5"><path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4"></path><path d="M9 18c-4.51 2-5-2-7-2"></path></svg>
                        <span class="sr-only">GitHub</span>
                    </li>
                </ul>
                <div class="newsletter-form">
                    <div class="newsletter-form-title">
                        <h3>Suscríbete a nuestro boletín</h3>
                    </div>
                    <div class="newsletter-form-content">
                        <form action="#" method="post" id="newsletter-form">
                            <div class="newsletter-input">
                                <label for="newsletter-email" class="sr-only">Email</label>
                                <input type="email" name="newsletter-email" id="newsletter-email" placeholder="Ingresa tu email" class="input-text" />
                            </div>
                            <button type="submit" title="Submit" class="button">
                                <span>Suscribirse</span>
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
