<div class="personal-footer-theme">
    <div class="footer-content">
        <div class="footer-content-item">
            <div class="footer-content-item-title">
                <h3>Sobre nosotros</h3>
            </div>
            <div class="footer-content-item-content">
                <ul>
                    <li><a href="#">Nuestra historia</a></li>
                    <li><a href="#">Trabaja con nosotros</a></li>
                    <li><a href="#">Prensa</a></li>
                </ul>
            </div>
        </div>
        <div class="footer-content-item">
            <div class="footer-content-item-title">
                <h3>Soporte</h3>
            </div>
            <div class="footer-content-item-content">
                <ul>
                    <li><a href="#">Centro de ayuda</a></li>
                    <li><a href="#">Devoluciones</a></li>
                    <li><a href="#">Información de envío</a></li>
                </ul>
            </div>
        </div>
        <div class="footer-content-item">
            <div class="footer-content-item-title">
                <h3>Legal</h3>
            </div>
            <div class="footer-content-item-content">
                <ul>
                    <li><a href="#">Políticas de privacidad</a></li>
                    <li><a href="#">Terminos y condiciones</a></li>
                    <li><a href="#">Política de cookies</a></li>
                </ul>
            </div>
        </div>
        <div class="footer-content-item">
            <div class="footer-content-item-title">
                <h3>Conecta con nosotros</h3>
            </div>
            <div class="footer-content-item-content">
                <ul>
                    <li><a href="#">Twitter logo</a></li>
                    <li><a href="#">Instagram logo</a></li>
                    <li><a href="#">GitHub logo</a></li>
                </ul>
                <div class="newsletter-form">
                    <div class="newsletter-form-title">
                        <h3>Suscríbete a nuestro boletín</h3>
                    </div>
                    <div class="newsletter-form-content">
                        <form action="#" method="post" id="newsletter-form">
                            <div class="newsletter-input">
                                <label for="newsletter-email" class="sr-only">Email</label>
                                <input type="email" name="newsletter-email" id="newsletter-email" placeholder="Email" class="input-text" />
                            </div>
                            <button type="submit" title="Submit" class="button">
                                <span>Submit</span>
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
